#!/bin/sh

# make root folder RW
start() {
        mount -o remount,rw /
        status=$?
        return "$status"
}

stop() {
        return "0"
}

restart() {
        stop
        sleep 1
        start
}

case "$1" in
        start|stop|restart)
                "$1";;
        reload)
                # Restart, since there is no true "reload" feature.
                restart;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac
